# Cloud Build configuration to run database migrations
# Run via: gcloud builds submit --config=migrations/cloudbuild.migration.yaml

steps:
  # Run pending bookings migration (Voice Agent POC)
  - name: 'gcr.io/$PROJECT_ID/cloud-builders-python:3.12'
    id: 'pending-bookings-migration'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install sqlalchemy psycopg2-binary

        DB_PASSWORD=$$(gcloud secrets versions access latest --secret=db-password --project=$PROJECT_ID)
        export DATABASE_URL="postgresql://postgres:$${DB_PASSWORD}@10.97.0.3:5432/parallel_universe_db"

        python migrations/run_pending_bookings_migration.py

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'
